### ISSUE TITLE
tags and categories for bibtex entry

### ISSUE THREAD

**Issue by laszewsk** [wowchemy/hugo-academic-cli#100]
I llke to associate to a bib file new fields that are used within hugo academic when creating the bibliography

I tried simply adding a 

tags: "class book"
categories: "ai"

to the bibtex entry and ran the import script. However when I look into the index.md file it renders only as

tags: []
categories: []

How can I use them directly from bibtex?

**Comment by gcushen** [comment]
Duplicate of https://github.com/wowchemy/hugo-academic-cli/issues/48
