### ISSUE TITLE
Fails to create publication if other publication exists from the same year

### ISSUE THREAD

**Issue by HoniSanders** [wowchemy/hugo-academic-cli#102]
I am running on a .bib file that has multiple references.  I ran `academic import --bibtex export.bib`.  It created a subfolder for each publication of form author-year.  Two references have the same first author and year.  I get the following warning `07:00:25PM WARNING: Skipping creation of content/publication/sanders-2020 as it already exists. To overwrite, add the --overwrite argument` and the folder for the second reference does not get created.

**Comment by gcushen** [comment]
The Biblatex ID is currently used as the publication folder name - you might wish to check that you set unique IDs in your reference manager.
