### ISSUE TITLE
--bibtex is a compulsory argument?

### ISSUE THREAD

**Issue by karthikraman** [wowchemy/hugo-academic-cli#145]
https://github.com/GetRD/academic-file-converter/blob/e2ccb0cbcf3842a5e5817f22472ee00b8375652b/README.md?plain=1#L74

This did not work for me in Hugo Academic CLI v0.8.1. If I added `--bibtex` it worked perfectly. Without it, I got not output, or warnings either.

Thanks for building such a wonderful tool!

**Comment by gcushen** [comment]
No, there is no such option in the current version, that's why there is no such option documented in the current version. If you want to verify this, you can see this in the code at https://github.com/GetRD/academic-file-converter/blob/e2ccb0cbcf3842a5e5817f22472ee00b8375652b/academic/cli.py

**Comment by gcushen** [comment]
It appears you are trying to use an ancient version. I recommend to use the current version.
