### ISSUE TITLE
Migrate config/params TOML to YAML

### ISSUE THREAD

**Issue by ionlights** [wowchemy/hugo-academic-cli#86]
This may not belong here, but I've found myself having to manually diff changes between `config.toml` and `params.toml` between Wowchemy versions.

I'm not sure what the failure modes might be, but adding new config/params options anytime those new changes are made would be good, I think? 

The use of migrating from TOML to YAML is that `ruamel.yaml` supports round-trip comments. I don't believe the `toml` pypi package supports that.

**Comment by gcushen** [comment]
It's interesting that you mentioned this.

We use YAML for some internal `config.yaml` files, such as for the Test site at https://github.com/wowchemy/wowchemy-hugo-modules/blob/master/wowchemy/test/config.yaml , primarily to keep things simpler so both front matter and config are in YAML. We have been converting the remaining TOML front matter in templates to YAML as GitHub still does not support TOML (even though TOML was created by and named after Tom, the founder of GitHub).

We have worked on some ideas for an upgrader tool in the past. If we were to create a new repo for such a tool, we would probably use either Go (to avoid any client dependencies and align with Hugo) or JS (to create a web-based tool, similar in some respects to how Hugo Server spawns a browser window). Would you be interested in contributing to such a project?
