### ISSUE TITLE
Tags are being imported with additional quotes

### ISSUE THREAD

**Issue by JMante1** [wowchemy/hugo-academic-cli#89]
When the import is run all tags are imported as '"Tag 1"', '"Tag2"' etc. The additional double quotes inside the single quotes cause issues when using the tags with the website

**Comment by gcushen** [comment]
Thanks, it appears to be an artifact from #68 . I've just attempted a fix.

Try:

```
pip3 install -U git+https://github.com/wowchemy/hugo-academic-cli.git
```

**Comment by JMante1** [comment]
Hi, I have tried that and the index files are still created with the additional quotations

**Comment by charrismatic** [comment]
I just followed the recommended steps above to update the hugo-cli to the latest version and I'm still getting the extra quotes in the tag field
